FROM nginx:mainline-alpine
EXPOSE 3000/tcp
ENV CGI_SERVER=gitweb-cgi
ENV CGI_PORT=9000
RUN apk add --update --no-cache \
        git-gitweb

COPY ./git.conf.template /etc/nginx/templates/default.conf.template
